/* compilador.java */
/* Generated By:JavaCC: Do not edit this line. compilador.java */
import java.util.*;
import java.util.ArrayList;
import java.util.List;
class compilador implements compiladorConstants {
        public static List <String> listaB = new ArrayList<String> ();
        public static void Contador(String Campo)
        {
                int Ubicacion=compilador.listaB.indexOf(Campo);
                if (Ubicacion==-1)
                {
                        compilador.listaB.add(Campo);
                        Ubicacion=compilador.listaB.indexOf(Campo);
                        System.out.print(Ubicacion);
                }
                else
                {
                        System.out.print(Ubicacion);
                }
        }
        public static void main (String[]args)throws ParseException
        {
                try
                {
                        compilador analizador = new compilador(System.in);
                        analizador.Inicio();
                        System.out.print("Finished");
                }
                catch(ParseException e)
                {
                        System.out.println(e.getMessage());
                        System.out.print("Unfinished");
                }
        }

  static final public void Inicio() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case numero:{
        jj_consume_token(numero);
        break;
        }
      case ID:{
        jj_consume_token(ID);
        break;
        }
      case letra_S:{
        jj_consume_token(letra_S);
        break;
        }
      case letra:{
        jj_consume_token(letra);
        break;
        }
      case Omatematicos:{
        jj_consume_token(Omatematicos);
        break;
        }
      case PAR_IZQ:{
        jj_consume_token(PAR_IZQ);
        break;
        }
      case PAR_DER:{
        jj_consume_token(PAR_DER);
        break;
        }
      case LLAVE_IZQ:{
        jj_consume_token(LLAVE_IZQ);
        break;
        }
      case LLAVE_DER:{
        jj_consume_token(LLAVE_DER);
        break;
        }
      case COR_IZQ:{
        jj_consume_token(COR_IZQ);
        break;
        }
      case COR_DER:{
        jj_consume_token(COR_DER);
        break;
        }
      case PUNTO:{
        jj_consume_token(PUNTO);
        break;
        }
      case COMA:{
        jj_consume_token(COMA);
        break;
        }
      case PUNTO_Y_COMA:{
        jj_consume_token(PUNTO_Y_COMA);
        break;
        }
      case DOS_PUNTOS:{
        jj_consume_token(DOS_PUNTOS);
        break;
        }
      case ARROBA:{
        jj_consume_token(ARROBA);
        break;
        }
      case guionbajo:{
        jj_consume_token(guionbajo);
        break;
        }
      case ASIGANCION:{
        jj_consume_token(ASIGANCION);
        break;
        }
      case COMILLA_DOBLE:{
        jj_consume_token(COMILLA_DOBLE);
        break;
        }
      case COMILLA:{
        jj_consume_token(COMILLA);
        break;
        }
      case alias:{
        jj_consume_token(alias);
        break;
        }
      case Void:{
        jj_consume_token(Void);
        break;
        }
      case system:{
        jj_consume_token(system);
        break;
        }
      case random:{
        jj_consume_token(random);
        break;
        }
      case Nespacio:{
        jj_consume_token(Nespacio);
        break;
        }
      case caso:{
        jj_consume_token(caso);
        break;
        }
      case cerrar:{
        jj_consume_token(cerrar);
        break;
        }
      case sobrecarga:{
        jj_consume_token(sobrecarga);
        break;
        }
      case interfaz:{
        jj_consume_token(interfaz);
        break;
        }
      case Pausar:{
        jj_consume_token(Pausar);
        break;
        }
      case Faritmetica:{
        jj_consume_token(Faritmetica);
        break;
        }
      case Ftrigonometrica:{
        jj_consume_token(Ftrigonometrica);
        break;
        }
      case Flineas:{
        jj_consume_token(Flineas);
        break;
        }
      case Fstring:{
        jj_consume_token(Fstring);
        break;
        }
      case Flambda:{
        jj_consume_token(Flambda);
        break;
        }
      case Fmensaje:{
        jj_consume_token(Fmensaje);
        break;
        }
      case Flimpiar:{
        jj_consume_token(Flimpiar);
        break;
        }
      case Ologicos:{
        jj_consume_token(Ologicos);
        break;
        }
      case Orelacionales:{
        jj_consume_token(Orelacionales);
        break;
        }
      case condicional:{
        jj_consume_token(condicional);
        break;
        }
      case defaults:{
        jj_consume_token(defaults);
        break;
        }
      case acceso:{
        jj_consume_token(acceso);
        break;
        }
      case booleano:{
        jj_consume_token(booleano);
        break;
        }
      case ciclos:{
        jj_consume_token(ciclos);
        break;
        }
      case salto:{
        jj_consume_token(salto);
        break;
        }
      case Tdato:{
        jj_consume_token(Tdato);
        break;
        }
      case EDD:{
        jj_consume_token(EDD);
        break;
        }
      case etiquetas:{
        jj_consume_token(etiquetas);
        break;
        }
      case dentro:{
        jj_consume_token(dentro);
        break;
        }
      case thread:{
        jj_consume_token(thread);
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Void:
      case system:
      case random:
      case Nespacio:
      case caso:
      case cerrar:
      case sobrecarga:
      case interfaz:
      case Pausar:
      case Faritmetica:
      case Ftrigonometrica:
      case Fstring:
      case Flambda:
      case Flineas:
      case Fmensaje:
      case Flimpiar:
      case Ologicos:
      case Orelacionales:
      case condicional:
      case defaults:
      case acceso:
      case booleano:
      case ciclos:
      case salto:
      case Tdato:
      case EDD:
      case etiquetas:
      case dentro:
      case thread:
      case ASIGANCION:
      case alias:
      case PAR_IZQ:
      case PAR_DER:
      case LLAVE_IZQ:
      case LLAVE_DER:
      case COR_IZQ:
      case COR_DER:
      case PUNTO:
      case COMA:
      case PUNTO_Y_COMA:
      case DOS_PUNTOS:
      case COMILLA:
      case COMILLA_DOBLE:
      case ARROBA:
      case guionbajo:
      case Omatematicos:
      case numero:
      case ID:
      case letra_S:
      case letra:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(0);
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public compiladorTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xfffffffe,0xfffffffe,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x7ffff,0x7ffff,};
	}

  /** Constructor with InputStream. */
  public compilador(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public compilador(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new compiladorTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public compilador(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new compiladorTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new compiladorTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public compilador(compiladorTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(compiladorTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[55];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 2; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 55; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
